---
# vars file for mongodb

mongodb__supported_version: [ 3.2, 3.4, 3.6, 4.0 ]
mongodb__apt_repo:
  Debian: "deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/{{ mongodb__version }} main"
  Ubuntu: "deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb__version }} multiverse"
mongodb__configfile: "/etc/mongod.conf"
